import { Flex } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Header from "../components/Header";
import SubmitGoalForm from "../components/SubmitGoalForm";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Raise The Stake</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
        <Flex alignItems="center" justifyContent="center" mt={2}>
          <SubmitGoalForm />
        </Flex>
      </main>
    </div>
  );
};

export default Home;
